const WALLET_MANAGER_PATH = '/walletManager'

const DASHBOARD_PATH = '/dashboard'
const DASHBOARD_ABSOLUTE_PATH = WALLET_MANAGER_PATH + DASHBOARD_PATH

export {
  WALLET_MANAGER_PATH,
  DASHBOARD_PATH,
  DASHBOARD_ABSOLUTE_PATH
}
